"""
ParaSol Dashboard
==================
Meteorological and Photovoltaic Performance Monitoring Panel
with Digital Twin Integration (Early Failure Detection).
"""
import datetime
from pathlib import Path
import joblib
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st
# =====================================================================
# PAGE CONFIGURATION (Must be the first Streamlit command)
# =====================================================================
st.set_page_config(
    layout="wide",
    initial_sidebar_state="expanded",
    page_title="ParaSol Dashboard"
)
LOGO_URL = "https://www.emiliojuarez.es/imgs/logo-oss.jpg"
CREATOR_LINK = "https://linkedin.com/in/cristian-carretero-fernandez"
# Absolute paths to data
FLEET_DATA_PATH = Path("data/aggregated/outdoor/meteo_mppt_10min.parquet")
SURVIVAL_DATA_PATH = Path("data/survival/outdoor/survival_dataset.parquet")
ARTIFACTS_PATH = Path("data/anomaly/artifacts/early_failure_artifacts.joblib")
# =====================================================================
# STYLES
# =====================================================================
def load_styles() -> None:
    """Loads external CSS and injects it into the application."""
    try:
        with open("assets/style.css", encoding="utf-8") as f:
            st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
    except FileNotFoundError:
        pass
# =====================================================================
# DATA LOADING AND CACHING
# =====================================================================
@st.cache_data(show_spinner=False)
def load_global_data() -> pd.DataFrame:
    try:
        df = pd.read_parquet(FLEET_DATA_PATH)
        if df.index.name == "Timestamp":
            df = df.reset_index()
        df["Timestamp"] = pd.to_datetime(df["Timestamp"])
        df.set_index("Timestamp", inplace=True)
        return df
    except Exception as e:
        st.error(f"Error loading the fleet dataset: {e}")
        return pd.DataFrame()
@st.cache_data(show_spinner=False)
def load_survival_data() -> pd.DataFrame:
    try:
        df = pd.read_parquet(SURVIVAL_DATA_PATH)
        df["Timestamp"] = pd.to_datetime(df["Timestamp"])
        df.set_index("Timestamp", inplace=True)
        return df
    except Exception as e:
        st.error(f"Error loading the survival dataset: {e}")
        return pd.DataFrame()
@st.cache_resource(show_spinner=False)
def load_ml_artifacts() -> dict:
    """Loads the Digital Twin brain generated by XGBoost."""
    try:
        if ARTIFACTS_PATH.exists():
            return joblib.load(ARTIFACTS_PATH)
    except Exception as e:
        st.warning(f"Failed to load Digital Twin artifacts: {e}")
    return {}
# =====================================================================
# ADVANCED PLOTLY CHART GENERATION
# =====================================================================
def create_plotly_chart(df, y_cols, color_seq=None, central_metric="Mean", band_min_col=None, band_max_col=None):
    if df.empty:
        return go.Figure()
    fig = go.Figure()
    if isinstance(y_cols, str):
        y_cols = [y_cols]
    if color_seq is None:
        color_seq = ["#36B9CC", "#1E293B", "#F59E0B", "#3B82F6", "#10B981", "#8B5CF6", "#F43F5E", "#64748B"]

    agg_func = "median" if central_metric == "Median" else "mean"
    label_stat = "Median" if central_metric == "Median" else "Mean"
    def hex_to_rgba(hex_color, alpha=0.25):
        hex_color = hex_color.lstrip("#")
        r, g, b = tuple(int(hex_color[i:i + 2], 16) for i in (0, 2, 4))
        return f"rgba({r},{g},{b},{alpha})"
    has_bands = band_min_col and band_max_col and band_min_col in df.columns and band_max_col in df.columns
    min_dt = df.index.min()
    max_dt = df.index.max()
    duration_days = (max_dt - min_dt).total_seconds() / 86400.0
    if duration_days <= 1.0:
        for i, col in enumerate(y_cols):
            c = color_seq[i % len(color_seq)]
            name = str(col)
            fig.add_trace(go.Scatter(x=df.index, y=df[col], mode="lines+markers", name=name, legendgroup=name, line=dict(color=c, width=1.5), marker=dict(size=4), visible=True, connectgaps=True))
        updatemenus_config = []

    elif duration_days <= 7.0:
        df_1h_main = df.resample("1h").agg(agg_func, numeric_only=True)
        df_1h_min = df.resample("1h").min(numeric_only=True)
        df_1h_max = df.resample("1h").max(numeric_only=True)
        df_1d_main = df.resample("1D").agg(agg_func, numeric_only=True)
        df_1d_min = df.resample("1D").min(numeric_only=True)
        df_1d_max = df.resample("1D").max(numeric_only=True)
        for i, col in enumerate(y_cols):
            c = color_seq[i % len(color_seq)]
            c_fill = hex_to_rgba(c, 0.25)
            name = str(col)
            use_band = has_bands and col in ["ModuleTemp_Mean_C", "ModuleTemp_Median_C"]
            b_min = band_min_col if use_band else col
            b_max = band_max_col if use_band else col

            fig.add_trace(go.Scatter(x=df.index, y=df[col], mode="lines+markers", name=name, legendgroup=name, line=dict(color=c, width=1.5), marker=dict(size=4), visible=True, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1h_min.index, y=df_1h_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1h_max.index, y=df_1h_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1h_main.index, y=df_1h_main[col], mode="lines+markers", name=f"{name} ({label_stat} 1H)", legendgroup=name, line=dict(color=c, width=2.0), marker=dict(size=5), visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_min.index, y=df_1d_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_max.index, y=df_1d_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_main.index, y=df_1d_main[col], mode="lines+markers", name=f"{name} ({label_stat} 1D)", legendgroup=name, line=dict(color=c, width=2.5), marker=dict(size=6), visible=False, connectgaps=True))

        n = len(y_cols)
        vis_orig = ([True, False, False, False, False, False, False]) * n
        vis_1h   = ([False, True, True, True, False, False, False]) * n
        vis_1d   = ([False, False, False, False, True, True, True]) * n

        trace_indices = list(range(7 * n))

        buttons_agg = [
            dict(label="Native (10 min)", method="restyle", args=[{"visible": vis_orig}, trace_indices]),
            dict(label=f"{label_stat} Hourly (1H)", method="restyle", args=[{"visible": vis_1h}, trace_indices]),
            dict(label=f"{label_stat} Daily (1D)", method="restyle", args=[{"visible": vis_1d}, trace_indices]),
        ]
        updatemenus_config = [
            dict(type="buttons", direction="right", buttons=buttons_agg, active=0, showactive=True,
                 x=1, xanchor="right", y=-0.15, yanchor="top", font=dict(size=11, color="#1E293B"),
                 bgcolor="#F8FAFC", bordercolor="#E2E8F0")
        ]

    elif duration_days <= 30.0:
        df_1h_main = df.resample("1h").agg(agg_func, numeric_only=True)
        df_1h_min = df.resample("1h").min(numeric_only=True)
        df_1h_max = df.resample("1h").max(numeric_only=True)
        
        df_6h_main = df.resample("6h").agg(agg_func, numeric_only=True)
        df_6h_min = df.resample("6h").min(numeric_only=True)
        df_6h_max = df.resample("6h").max(numeric_only=True)
        
        df_1d_main = df.resample("1D").agg(agg_func, numeric_only=True)
        df_1d_min = df.resample("1D").min(numeric_only=True)
        df_1d_max = df.resample("1D").max(numeric_only=True)
        
        df_7d_main = df.resample("7D").agg(agg_func, numeric_only=True)
        df_7d_min = df.resample("7D").min(numeric_only=True)
        df_7d_max = df.resample("7D").max(numeric_only=True)
        
        for i, col in enumerate(y_cols):
            c = color_seq[i % len(color_seq)]
            c_fill = hex_to_rgba(c, 0.25)
            name = str(col)
            use_band = has_bands and col in ["ModuleTemp_Mean_C", "ModuleTemp_Median_C"]
            b_min = band_min_col if use_band else col
            b_max = band_max_col if use_band else col

            # 1H (Por defecto visible)
            fig.add_trace(go.Scatter(x=df_1h_min.index, y=df_1h_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=True, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1h_max.index, y=df_1h_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=True, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1h_main.index, y=df_1h_main[col], mode="lines+markers", name=f"{name} ({label_stat} 1H)", legendgroup=name, line=dict(color=c, width=2.0), marker=dict(size=5), visible=True, connectgaps=True))
            
            # 6H
            fig.add_trace(go.Scatter(x=df_6h_min.index, y=df_6h_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_6h_max.index, y=df_6h_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_6h_main.index, y=df_6h_main[col], mode="lines+markers", name=f"{name} ({label_stat} 6H)", legendgroup=name, line=dict(color=c, width=2.0), marker=dict(size=5), visible=False, connectgaps=True))

            # 1D
            fig.add_trace(go.Scatter(x=df_1d_min.index, y=df_1d_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_max.index, y=df_1d_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_main.index, y=df_1d_main[col], mode="lines+markers", name=f"{name} ({label_stat} 1D)", legendgroup=name, line=dict(color=c, width=2.5), marker=dict(size=6), visible=False, connectgaps=True))
            
            # 7D
            fig.add_trace(go.Scatter(x=df_7d_min.index, y=df_7d_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_7d_max.index, y=df_7d_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_7d_main.index, y=df_7d_main[col], mode="lines+markers", name=f"{name} ({label_stat} 7D)", legendgroup=name, line=dict(color=c, width=2.5), marker=dict(size=8), visible=False, connectgaps=True))

        n = len(y_cols)
        vis_1h = ([True, True, True, False, False, False, False, False, False, False, False, False]) * n
        vis_6h = ([False, False, False, True, True, True, False, False, False, False, False, False]) * n
        vis_1d = ([False, False, False, False, False, False, True, True, True, False, False, False]) * n
        vis_7d = ([False, False, False, False, False, False, False, False, False, True, True, True]) * n

        trace_indices = list(range(12 * n))

        buttons_agg = [
            dict(label=f"{label_stat} Hourly (1H)", method="restyle", args=[{"visible": vis_1h}, trace_indices]),
            dict(label=f"{label_stat} 6-Hourly (6H)", method="restyle", args=[{"visible": vis_6h}, trace_indices]),
            dict(label=f"{label_stat} Daily (1D)", method="restyle", args=[{"visible": vis_1d}, trace_indices]),
            dict(label=f"{label_stat} Weekly (7D)", method="restyle", args=[{"visible": vis_7d}, trace_indices]),
        ]
        updatemenus_config = [
            dict(type="buttons", direction="right", buttons=buttons_agg, active=0, showactive=True,
                 x=1, xanchor="right", y=-0.15, yanchor="top", font=dict(size=11, color="#1E293B"),
                 bgcolor="#F8FAFC", bordercolor="#E2E8F0")
        ]

    else:
        df_6h_main = df.resample("6h").agg(agg_func, numeric_only=True)
        df_6h_min = df.resample("6h").min(numeric_only=True)
        df_6h_max = df.resample("6h").max(numeric_only=True)
        
        df_1d_main = df.resample("1D").agg(agg_func, numeric_only=True)
        df_1d_min = df.resample("1D").min(numeric_only=True)
        df_1d_max = df.resample("1D").max(numeric_only=True)
        
        df_7d_main = df.resample("7D").agg(agg_func, numeric_only=True)
        df_7d_min = df.resample("7D").min(numeric_only=True)
        df_7d_max = df.resample("7D").max(numeric_only=True)
        
        df_30d_main = df.resample("30D").agg(agg_func, numeric_only=True)
        df_30d_min = df.resample("30D").min(numeric_only=True)
        df_30d_max = df.resample("30D").max(numeric_only=True)
        
        for i, col in enumerate(y_cols):
            c = color_seq[i % len(color_seq)]
            c_fill = hex_to_rgba(c, 0.25)
            name = str(col)
            use_band = has_bands and col in ["ModuleTemp_Mean_C", "ModuleTemp_Median_C"]
            b_min = band_min_col if use_band else col
            b_max = band_max_col if use_band else col

            # 6H
            fig.add_trace(go.Scatter(x=df_6h_min.index, y=df_6h_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_6h_max.index, y=df_6h_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_6h_main.index, y=df_6h_main[col], mode="lines+markers", name=f"{name} ({label_stat} 6H)", legendgroup=name, line=dict(color=c, width=2.0), marker=dict(size=5), visible=False, connectgaps=True))

            # 1D (Por defecto visible en historical)
            fig.add_trace(go.Scatter(x=df_1d_min.index, y=df_1d_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=True, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_max.index, y=df_1d_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=True, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_1d_main.index, y=df_1d_main[col], mode="lines+markers", name=f"{name} ({label_stat} 1D)", legendgroup=name, line=dict(color=c, width=2.5), marker=dict(size=6), visible=True, connectgaps=True))
            
            # 7D
            fig.add_trace(go.Scatter(x=df_7d_min.index, y=df_7d_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_7d_max.index, y=df_7d_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_7d_main.index, y=df_7d_main[col], mode="lines+markers", name=f"{name} ({label_stat} 7D)", legendgroup=name, line=dict(color=c, width=2.5), marker=dict(size=8), visible=False, connectgaps=True))
            
            # 30D
            fig.add_trace(go.Scatter(x=df_30d_min.index, y=df_30d_min[b_min], mode="lines", line=dict(width=0), name=f"Min {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_30d_max.index, y=df_30d_max[b_max], mode="lines", line=dict(width=0), fill="tonexty", fillcolor=c_fill, name=f"Max {name}", legendgroup=name, showlegend=False, visible=False, connectgaps=True))
            fig.add_trace(go.Scatter(x=df_30d_main.index, y=df_30d_main[col], mode="lines+markers", name=f"{name} ({label_stat} 30D)", legendgroup=name, line=dict(color=c, width=2.5), marker=dict(size=10), visible=False, connectgaps=True))

        n = len(y_cols)
        vis_6h = ([True, True, True, False, False, False, False, False, False, False, False, False]) * n
        vis_1d = ([False, False, False, True, True, True, False, False, False, False, False, False]) * n
        vis_7d = ([False, False, False, False, False, False, True, True, True, False, False, False]) * n
        vis_30d = ([False, False, False, False, False, False, False, False, False, True, True, True]) * n

        trace_indices = list(range(12 * n))

        buttons_agg = [
            dict(label=f"{label_stat} 6-Hourly (6H)", method="restyle", args=[{"visible": vis_6h}, trace_indices]),
            dict(label=f"{label_stat} Daily (1D)", method="restyle", args=[{"visible": vis_1d}, trace_indices]),
            dict(label=f"{label_stat} Weekly (7D)", method="restyle", args=[{"visible": vis_7d}, trace_indices]),
            dict(label=f"{label_stat} Monthly (30D)", method="restyle", args=[{"visible": vis_30d}, trace_indices]),
        ]
        updatemenus_config = [
            dict(type="buttons", direction="right", buttons=buttons_agg, active=1, showactive=True,
                 x=1, xanchor="right", y=-0.15, yanchor="top", font=dict(size=11, color="#1E293B"),
                 bgcolor="#F8FAFC", bordercolor="#E2E8F0")
        ]
    fig.update_layout(
        margin=dict(l=10, r=10, t=10, b=60), plot_bgcolor="white", paper_bgcolor="white",
        hovermode="x unified", legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        updatemenus=updatemenus_config,
    )
    fig.update_xaxes(showgrid=True, gridcolor="#F1F5F9")
    fig.update_yaxes(showgrid=True, gridcolor="#F1F5F9")
    return fig
# =====================================================================
# ACCUMULATED BAR CHART
# =====================================================================
def create_accumulated_bar_chart(df, col, color, ylabel, conversion_factor):
    if df.empty or col not in df.columns:
        return go.Figure()
    df_calc = df[[col]].copy()
    df_calc['Dose'] = df_calc[col] * conversion_factor
    min_dt = df_calc.index.min()
    max_dt = df_calc.index.max()
    duration_days = (max_dt - min_dt).total_seconds() / 86400.0
    def generate_labels_and_widths(indices, days):
        labels = []
        widths = []
        for date in indices:
            if days < 1:
                theoretical_end = date + pd.Timedelta(hours=1)
                end_date = min(theoretical_end, max_dt)
                labels.append(f"{date.strftime('%Y-%m-%d %H:%M')} - {end_date.strftime('%H:%M')}")
                widths.append(3600000 * 0.95)
            else:
                theoretical_end = date + pd.Timedelta(days=days - 1)
                end_date = min(theoretical_end, max_dt)
                real_days = (end_date.date() - date.date()).days + 1
                if real_days <= 1:
                    labels.append(date.strftime('%Y-%m-%d'))
                else:
                    labels.append(f"{date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")
                widths.append((real_days * 86400000) * 0.95)
        return labels, widths
    fig = go.Figure()
    def add_bar_trace(x_data, y_data, days, name_suffix, is_visible):
        if len(x_data) == 0:
            return
        custom_texts, widths = generate_labels_and_widths(x_data, days)
        fig.add_trace(go.Bar(
            x=x_data, y=y_data, customdata=custom_texts, name=f"{name_suffix} Dose",
            marker_color=color, marker_line_color='white', marker_line_width=1.5,
            opacity=0.9, width=widths, offset=0,
            hovertemplate="<b>%{customdata}</b><br>Accumulated Dose: %{y:.2f} " + ylabel + "<extra></extra>",
            visible=is_visible
        ))
    if duration_days <= 1.0:
        df_1h = df_calc.resample("1h")['Dose'].sum().dropna()
        add_bar_trace(df_1h.index, df_1h.values, 1 / 24, "Hourly (1H)", True)
        updatemenus_config = []
    elif duration_days <= 7.0:
        df_1h = df_calc.resample("1h")['Dose'].sum().dropna()
        df_1d = df_calc.resample("1D")['Dose'].sum().dropna()
        add_bar_trace(df_1h.index, df_1h.values, 1 / 24, "Hourly (1H)", True)
        add_bar_trace(df_1d.index, df_1d.values, 1, "Daily (1D)", False)
        buttons_agg = [
            dict(label="Hourly (1H)", method="update", args=[{"visible": [True, False]}]),
            dict(label="Daily (1D)", method="update", args=[{"visible": [False, True]}]),
        ]
        updatemenus_config = [
            dict(type="buttons", direction="right", buttons=buttons_agg, active=0, showactive=True,
                 x=1, xanchor="right", y=-0.15, yanchor="top", font=dict(size=11, color="#1E293B"),
                 bgcolor="#F8FAFC", bordercolor="#E2E8F0")
        ]
    elif duration_days <= 30.0:
        df_1d = df_calc.resample("1D")['Dose'].sum().dropna()
        df_7d = df_calc.resample("7D")['Dose'].sum().dropna()
        add_bar_trace(df_1d.index, df_1d.values, 1, "Daily (1D)", True)
        add_bar_trace(df_7d.index, df_7d.values, 7, "Weekly (7D)", False)
        buttons_agg = [
            dict(label="Daily (1D)", method="update", args=[{"visible": [True, False]}]),
            dict(label="Weekly (7D)", method="update", args=[{"visible": [False, True]}]),
        ]
        updatemenus_config = [
            dict(type="buttons", direction="right", buttons=buttons_agg, active=0, showactive=True,
                 x=1, xanchor="right", y=-0.15, yanchor="top", font=dict(size=11, color="#1E293B"),
                 bgcolor="#F8FAFC", bordercolor="#E2E8F0")
        ]
    else:
        df_1d = df_calc.resample("1D")['Dose'].sum().dropna()
        df_7d = df_calc.resample("7D")['Dose'].sum().dropna()
        df_30d = df_calc.resample("30D")['Dose'].sum().dropna()
        add_bar_trace(df_1d.index, df_1d.values, 1, "Daily (1D)", True)
        add_bar_trace(df_7d.index, df_7d.values, 7, "Weekly (7D)", False)
        add_bar_trace(df_30d.index, df_30d.values, 30, "Monthly (30D)", False)
        buttons_agg = [
            dict(label="Daily (1D)", method="update", args=[{"visible": [True, False, False]}]),
            dict(label="Weekly (7D)", method="update", args=[{"visible": [False, True, False]}]),
            dict(label="Monthly (30D)", method="update", args=[{"visible": [False, False, True]}]),
        ]
        updatemenus_config = [
            dict(type="buttons", direction="right", buttons=buttons_agg, active=0, showactive=True,
                 x=1, xanchor="right", y=-0.15, yanchor="top", font=dict(size=11, color="#1E293B"),
                 bgcolor="#F8FAFC", bordercolor="#E2E8F0")
        ]
    fig.update_layout(
        margin=dict(l=10, r=10, t=10, b=60), plot_bgcolor="white", paper_bgcolor="white",
        hovermode="closest", bargap=0.0, legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        updatemenus=updatemenus_config,
    )
    fig.update_xaxes(showgrid=False)
    fig.update_yaxes(showgrid=True, gridcolor="#F1F5F9", title_text=ylabel)
    return fig
# =====================================================================
# T80 AND SURVIVAL_DAYS CALCULATION
# =====================================================================
def calculate_t80_and_survival(df: pd.DataFrame, irradiance_threshold: float = 100.0, consecutive_days: int = 3) -> dict:
    df = df.copy()
    df['Datetime'] = df.index
    df['Date_Day'] = df['Datetime'].dt.date
    df['Day_Zero'] = df.groupby('cell_name')['Datetime'].transform('min')
    df['Exposure_Days'] = (df['Datetime'] - df['Day_Zero']).dt.total_seconds() / 86400.0
    if 'POA_Irradiance_W_m2' in df.columns:
        daylight_df = df[df['POA_Irradiance_W_m2'] > irradiance_threshold].copy()
    else:
        daylight_df = df.copy()
    daily_df = (
        daylight_df.groupby(['cell_name', 'Date_Day'])
        .agg(pseudo_FF_max=('pseudo_FF', 'max'), Exposure_Days_max=('Exposure_Days', 'max'))
        .reset_index()
        .sort_values(by=['cell_name', 'Date_Day'])
    )
    first_3_days = daily_df.groupby('cell_name').head(3)
    idx_max_initial = first_3_days.groupby('cell_name')['pseudo_FF_max'].idxmax()
    initial_peak = first_3_days.loc[idx_max_initial, ['cell_name', 'Exposure_Days_max', 'pseudo_FF_max']].rename(
        columns={'pseudo_FF_max': 'pFF_initial', 'Exposure_Days_max': 'Peak_Day'}
    )
    daily_df = daily_df.merge(initial_peak, on='cell_name', how='left')
    daily_df['T80_threshold'] = daily_df['pFF_initial'] * 0.80

    daily_df['Is_Below_T80'] = (
        (daily_df['Exposure_Days_max'] >= daily_df['Peak_Day']) &
        (daily_df['pseudo_FF_max'] < daily_df['T80_threshold'])
    ).astype(int)
    day_zero_per_cell = df.groupby('cell_name')['Day_Zero'].first()
    result = {}
    for cell, group in daily_df.groupby('cell_name'):
        # Reset to a clean positional (0..n-1) index so streak-position
        # arithmetic below is always plain int arithmetic (avoids
        # ambiguous label-based lookups / operator type issues).
        group = group.sort_values('Date_Day').reset_index(drop=True)
        t80_threshold = float(group['T80_threshold'].iloc[0])

        streak = group['Is_Below_T80'].rolling(window=consecutive_days, min_periods=consecutive_days).sum()
        streak_mask = (streak == consecutive_days).to_numpy()

        if streak_mask.any():
            confirmation_pos = int(np.flatnonzero(streak_mask)[0])
            streak_start_pos = confirmation_pos - consecutive_days + 1

            death_exposure_day = float(
                pd.to_numeric(group['Exposure_Days_max'].iat[streak_start_pos], errors='coerce')
            )
            death_time = day_zero_per_cell[cell] + pd.Timedelta(days=death_exposure_day)
        else:
            death_time = None

        result[cell] = {'t80_threshold': t80_threshold, 'death_time': death_time}
    return result
def get_trace_color(fig, trace_name: str, default_color: str = "grey") -> str:
    for trace in fig.data:
        if trace.name == trace_name:
            return trace.line.color or trace.marker.color or default_color
    return default_color
# =====================================================================
# KPI UTILITIES
# =====================================================================
def calculate_delta_pct(actual, previous):
    if pd.isna(actual) or pd.isna(previous) or previous == 0:
        return None
    return ((actual - previous) / previous) * 100
def format_kpi(value, unit, decimals=1):
    return f"{value:.{decimals}f} {unit}" if pd.notna(value) else f"-- {unit}"
def format_delta(actual, previous):
    delta = calculate_delta_pct(actual, previous)
    return f"{delta:+.1f}%" if delta is not None else "N/A"
# =====================================================================
# TOOLBAR: TIME WINDOW SELECTION
# =====================================================================
def render_toolbar(min_date: datetime.date, max_date: datetime.date):
    with st.container(border=True):
        col_label, col_control = st.columns([1, 4], vertical_alignment="center")
        with col_label:
            st.markdown("**Time Window**")
        with col_control:
            time_window = st.segmented_control(
                "Time Window",
                options=["1D", "7D", "30D", "Historical", "Custom Dates"],
                default="1D",
                label_visibility="collapsed",
            )
        time_window = time_window or "1D"
        start_date, end_date = min_date, max_date

        if time_window == "Custom Dates":
            col_d1, col_d2, _ = st.columns([1, 1, 2])
            with col_d1:
                start_date = st.date_input("From", value=min_date)
            with col_d2:
                end_date = st.date_input("To", value=max_date)

    return time_window, start_date, end_date
# =====================================================================
# GLOBAL SIDEBAR: LOGO
# =====================================================================
def render_branding() -> None:
    st.logo(LOGO_URL, size="large", link=LOGO_URL)
dates_index = pd.date_range(start="2026-01-01", periods=100, freq="D")
plotly_config = {
    "modeBarButtonsToRemove": ["autoScale2d", "select2d", "lasso2d"],
    "displaylogo": False,
    "toImageButtonOptions": {
        "format": "png",
        "filename": "parasol_chart",
        "height": 600,
        "width": 1000,
        "scale": 2
    }
}
# =====================================================================
# VIEW 1: GENERAL OVERVIEW
# =====================================================================
def general_overview():
    st.sidebar.markdown(
        "<h4 style='font-size: 1.1rem; color: #1E293B; margin-bottom: 0;'>KPI Options</h4>",
        unsafe_allow_html=True
    )
    irradiance_type = st.sidebar.radio("Irradiance (KPI 1)", ["Mean", "Peak"])
    module_temp_type = st.sidebar.radio("Module Temp. (KPI 3)", ["Mean", "Median"])
    kpi4_type = st.sidebar.radio("Secondary Metric (KPI 4)", ["Radiation Dose", "Relative Humidity", "Absolute Humidity"])

    st.sidebar.divider()

    st.sidebar.markdown(
        "<h4 style='font-size: 1.1rem; color: #1E293B; margin-bottom: 0;'>Chart Aggregations</h4>",
        unsafe_allow_html=True
    )
    selected_metric = st.sidebar.radio(
        "Central Tendency",
        ["Mean", "Median"],
        index=0,
        help="Statistical metric applied to the temporal resampling of charts.",
    )

    st.sidebar.divider()
    st.sidebar.markdown(
        f"""
        <div style='text-align: center; font-size: 0.85rem; color: #64748B; margin-top: 1rem;'>
            Developed by <br>
            <a href='{CREATOR_LINK}' target='_blank' style='color: #36B9CC; text-decoration: none; font-weight: 600;'>
                Cristian Carretero
            </a>
        </div>
        """,
        unsafe_allow_html=True,
    )
    fleet_df = load_global_data()
    ml_artifacts = load_ml_artifacts()
    survival_df = load_survival_data()
    if not fleet_df.empty:
        max_date = pd.to_datetime(fleet_df.index.max()).date()
        min_date = pd.to_datetime(fleet_df.index.min()).date()
    else:
        max_date = datetime.date.today()
        min_date = max_date - datetime.timedelta(days=30)
    st.markdown("### ParaSol Station")
    st.caption("Historical and real-time environmental monitoring.")
    st.markdown("<div style='height: 0.4rem;'></div>", unsafe_allow_html=True)
    time_window, start_date, end_date = render_toolbar(min_date, max_date)
    st.markdown("<div style='height: 0.6rem;'></div>", unsafe_allow_html=True)
    plot_df, prev_df = pd.DataFrame(), pd.DataFrame()
    if not fleet_df.empty:
        max_timestamp = fleet_df.index.max()
        if time_window in ("1D", "7D", "30D"):
            days = {"1D": 1, "7D": 7, "30D": 30}[time_window]
            anchor_time = max_timestamp
            if anchor_time.hour == 0 and anchor_time.minute == 0 and anchor_time.second == 0:
                anchor_time -= pd.Timedelta(seconds=1)
            delta_start = pd.Timedelta(days=days - 1)
            start_dt = (anchor_time - delta_start).normalize()

            plot_df = fleet_df[fleet_df.index >= start_dt]
            delta_prev = pd.Timedelta(days=days)
            prev_df = fleet_df[(fleet_df.index >= (start_dt - delta_prev)) & (fleet_df.index < start_dt)]
        elif time_window == "Historical":
            plot_df = fleet_df.copy()
            prev_df = pd.DataFrame()
        elif time_window == "Custom Dates":
            if start_date > end_date:
                st.error("❌ **Selection Error:** The start date cannot be later than the end date.")
                st.stop()
            else:
                start_dt = pd.to_datetime(start_date)
                end_dt = pd.to_datetime(end_date) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)
                plot_df = fleet_df[(fleet_df.index >= start_dt) & (fleet_df.index <= end_dt)]
                if plot_df.empty:
                    st.error("❌ **No Records:** No data available for the selected period.")
                    st.stop()
                delta_dates = end_dt - start_dt
                prev_df = fleet_df[(fleet_df.index >= (start_dt - delta_dates)) & (fleet_df.index < start_dt)]
        plot_df = plot_df.dropna(how="all")
        if plot_df.empty:
            st.error(f"❌ **No Records:** No data available for the selected time window ({time_window}).")
            st.stop()

        if "POA_Irradiance_W_m2" in plot_df.columns:
            has_prev = not prev_df.empty
            if irradiance_type == "Mean":
                irr_act, kpi1_label = plot_df["POA_Irradiance_W_m2"].mean(), "Mean POA Irradiance"
                irr_prev = prev_df["POA_Irradiance_W_m2"].mean() if has_prev else np.nan
            else:
                irr_act, kpi1_label = plot_df["POA_Irradiance_W_m2"].max(), "Peak POA Irradiance"
                irr_prev = prev_df["POA_Irradiance_W_m2"].max() if has_prev else np.nan
            kpi1_val, kpi1_delta = format_kpi(irr_act, "W/m²", 0), format_delta(irr_act, irr_prev)
            t_amb_act = plot_df["AmbientTemp_C"].mean()
            t_amb_prev = prev_df["AmbientTemp_C"].mean() if has_prev else np.nan
            kpi2_val, kpi2_delta = format_kpi(t_amb_act, "°C", 1), format_delta(t_amb_act, t_amb_prev)
            temp_col = "ModuleTemp_Mean_C" if module_temp_type == "Mean" else "ModuleTemp_Median_C"
            kpi3_label = f"Module Temp. ({module_temp_type})"
            t_mod_act = plot_df[temp_col].mean()
            t_mod_prev = prev_df[temp_col].mean() if has_prev else np.nan
            kpi3_val, kpi3_delta = format_kpi(t_mod_act, "°C", 1), format_delta(t_mod_act, t_mod_prev)
            if kpi4_type == "Radiation Dose":
                kpi4_act = (plot_df["POA_Irradiance_W_m2"].sum() * (10 / 60)) / 1000
                kpi4_prev = (prev_df["POA_Irradiance_W_m2"].sum() * (10 / 60)) / 1000 if has_prev else np.nan
                kpi4_label, kpi4_val = "Accumulated Rad. Dose", format_kpi(kpi4_act, "kWh/m²", 1)
                kpi4_delta = format_delta(kpi4_act, kpi4_prev)
            elif kpi4_type == "Relative Humidity":
                hum_act = plot_df["RelativeHumidity_pct"].mean()
                hum_prev = prev_df["RelativeHumidity_pct"].mean() if has_prev else np.nan
                kpi4_label, kpi4_val = "Mean Relative Humidity", format_kpi(hum_act, "%", 1)
                kpi4_delta = format_delta(hum_act, hum_prev)
            else:
                ah_act = plot_df["AbsoluteHumidity_g_m3"].mean()
                ah_prev = prev_df["AbsoluteHumidity_g_m3"].mean() if has_prev else np.nan
                kpi4_label, kpi4_val = "Mean Absolute Humidity", format_kpi(ah_act, "g/m³", 2)
                kpi4_delta = format_delta(ah_act, ah_prev)
            st.markdown(f"#### Environmental Telemetry ({time_window})")
            col1, col2, col3, col4 = st.columns(4)
            col1.metric(kpi1_label, kpi1_val, kpi1_delta)
            col2.metric("Mean Ambient Temp.", kpi2_val, kpi2_delta)
            col3.metric(kpi3_label, kpi3_val, kpi3_delta)
            col4.metric(kpi4_label, kpi4_val, kpi4_delta)
            st.markdown("<div style='height: 1rem;'></div>", unsafe_allow_html=True)
            tab_irr, tab_temp, tab_rh, tab_ah = st.tabs(["POA Irradiance", "Temperatures", "Relative Humidity", "Absolute Humidity"])
            with tab_irr:
                st.markdown("##### Instantaneous POA Irradiance (W/m²)")
                fig1 = create_plotly_chart(plot_df, "POA_Irradiance_W_m2", ["#36B9CC"], central_metric=selected_metric)
                st.plotly_chart(fig1, width="stretch", config=plotly_config)
                st.markdown("<hr style='margin: 1rem 0; opacity: 0.3;'>", unsafe_allow_html=True)
                st.markdown("##### Accumulated Radiation Dose (kWh/m²)")
                fig_bar_irr = create_accumulated_bar_chart(plot_df, "POA_Irradiance_W_m2", "#36B9CC", "kWh/m²", conversion_factor=(10 / 60) / 1000)
                st.plotly_chart(fig_bar_irr, width="stretch", config=plotly_config)
            with tab_temp:
                st.markdown("##### Ambient Temperature vs. Module Temperature (°C)")
                mod_temp_col = "ModuleTemp_Mean_C" if module_temp_type == "Mean" else "ModuleTemp_Median_C"
                fig2 = create_plotly_chart(
                    plot_df,
                    ["AmbientTemp_C", mod_temp_col],
                    ["#1E293B", "#F59E0B"],
                    central_metric=selected_metric,
                    band_min_col="ModuleTemp_Min_C",
                    band_max_col="ModuleTemp_Max_C"
                )
                st.plotly_chart(fig2, width="stretch", config=plotly_config)
                st.markdown("<hr style='margin: 1rem 0; opacity: 0.3;'>", unsafe_allow_html=True)
                st.markdown("##### Accumulated Thermal Load on Module (°C·h)")
                fig_bar_temp = create_accumulated_bar_chart(plot_df, mod_temp_col, "#F59E0B", "°C·h", conversion_factor=10 / 60)
                st.plotly_chart(fig_bar_temp, width="stretch", config=plotly_config)
            with tab_rh:
                st.markdown("##### Relative Humidity (%)")
                fig3 = create_plotly_chart(plot_df, "RelativeHumidity_pct", ["#3B82F6"], central_metric=selected_metric)
                st.plotly_chart(fig3, width="stretch", config=plotly_config)
            with tab_ah:
                st.markdown("##### Absolute Humidity (g/m³)")
                fig4 = create_plotly_chart(plot_df, "AbsoluteHumidity_g_m3", ["#8B5CF6"], central_metric=selected_metric)
                st.plotly_chart(fig4, width="stretch", config=plotly_config)
                st.markdown("<hr style='margin: 1rem 0; opacity: 0.3;'>", unsafe_allow_html=True)
                st.markdown("##### Accumulated Humidity Dose (g/m³·h)")
                fig_bar_ah = create_accumulated_bar_chart(plot_df, "AbsoluteHumidity_g_m3", "#8B5CF6", "g/m³·h", conversion_factor=10 / 60)
                st.plotly_chart(fig_bar_ah, width="stretch", config=plotly_config)

    # =================================================================
    # OVERALL PERFORMANCE AND ML DIAGNOSTICS
    # =================================================================
    st.markdown(f"#### Overall Performance ({time_window})")
    power_cols = [col for col in plot_df.columns if 'power' in col.lower() or 'p_mpp' in col.lower()]
    CELL_AREA_M2 = 0.64 / 10000.0
    def safe_max(df_local, cols):
        if not cols or df_local.empty: return np.nan
        vals_sum = df_local[cols].sum(axis=1, min_count=1)
        return vals_sum.max() if not vals_sum.isna().all() else np.nan
    def calc_physical_pce(df_local, p_cols):
        if not p_cols or df_local.empty or 'POA_Irradiance_W_m2' not in df_local.columns: return np.nan
        mask = df_local['POA_Irradiance_W_m2'] > 10
        if not mask.any(): return np.nan
        pce_arrays = []
        for c in p_cols:
            incident_power_w = df_local.loc[mask, 'POA_Irradiance_W_m2'] * CELL_AREA_M2
            pce = df_local.loc[mask, c] / incident_power_w
            pce_arrays.append(pce)
        pce_df = pd.concat(pce_arrays)
        return pce_df.replace([0, np.inf, -np.inf], np.nan).mean() * 100
    max_power_act = safe_max(plot_df, power_cols)
    max_power_prev = safe_max(prev_df, power_cols)
    mean_pce_act = calc_physical_pce(plot_df, power_cols)
    mean_pce_prev = calc_physical_pce(prev_df, power_cols)
    total_energy_act = (plot_df["POA_Irradiance_W_m2"].sum() * (10 / 60)) / 1000 if not plot_df.empty else np.nan
    total_energy_prev = (prev_df["POA_Irradiance_W_m2"].sum() * (10 / 60)) / 1000 if not prev_df.empty else np.nan
    if pd.notna(max_power_act) and max_power_act < 1.0:
        kpi_p1_val = format_kpi(max_power_act * 1000, "mW", 1)
    else:
        kpi_p1_val = format_kpi(max_power_act, "W", 2)
    kpi_p1_delta = format_delta(max_power_act, max_power_prev)
    kpi_p2_val = format_kpi(total_energy_act, "kWh/m²", 1)
    kpi_p2_delta = format_delta(total_energy_act, total_energy_prev)
    kpi_p3_val = format_kpi(mean_pce_act, "%", 2)
    kpi_p3_delta = format_delta(mean_pce_act, mean_pce_prev)
    # -------------------------------------------------------------
    # Timezone-naive helpers (shared by KPI4, the lifecycle alert
    # section and the fleet comparison chart). Defining them here,
    # unconditionally, keeps them always bound regardless of which
    # branches below actually execute.
    # -------------------------------------------------------------
    min_t, max_t = None, None
    if not plot_df.empty:
        min_t = plot_df.index.min()
        max_t = plot_df.index.max()
        if getattr(min_t, "tzinfo", None) is not None:
            min_t = min_t.replace(tzinfo=None)
        if getattr(max_t, "tzinfo", None) is not None:
            max_t = max_t.replace(tzinfo=None)

    survival_naive_df = pd.DataFrame()
    if not survival_df.empty:
        survival_naive_df = survival_df.copy()
        survival_dt_index = pd.DatetimeIndex(survival_naive_df.index)
        if getattr(survival_dt_index, "tz", None) is not None:
            survival_dt_index = survival_dt_index.tz_localize(None)
        survival_naive_df.index = survival_dt_index
    # -------------------------------------------------------------
    # KPI 4: Digital Twin Dynamic Status
    # -------------------------------------------------------------
    df_summary_dyn = pd.DataFrame()
    if ml_artifacts and min_t is not None and max_t is not None and not survival_naive_df.empty:
        df_summary = ml_artifacts.get("summary_table", pd.DataFrame()).copy()

        # 1. Identify active cells (Timezone-naive to prevent Data Leakage)
        mask_surv_window = (survival_naive_df.index >= min_t) & (survival_naive_df.index <= max_t)
        cell_name_col = survival_naive_df["cell_name"]
        active_cells_window = pd.unique(cell_name_col[mask_surv_window])

        idx_present = df_summary.index.intersection(active_cells_window)
        df_summary_dyn = df_summary.loc[idx_present].copy()

        if not df_summary_dyn.empty:
            # Ensure clean dates without Timezones
            for col in ["t80_failure_date", "ml_alert_date"]:
                df_summary_dyn[col] = pd.to_datetime(df_summary_dyn[col])
                if getattr(df_summary_dyn[col].dt, 'tz', None) is not None:
                    df_summary_dyn[col] = df_summary_dyn[col].dt.tz_localize(None)
            # 2. Evaluate what occurred strictly BEFORE or DURING max_t
            df_summary_dyn["t80_occurred"] = df_summary_dyn["t80_failure_date"].notna() & (df_summary_dyn["t80_failure_date"] <= max_t)
            df_summary_dyn["ml_occurred"] = df_summary_dyn["ml_alert_date"].notna() & (df_summary_dyn["ml_alert_date"] <= max_t)

            # 3. MASK FUTURE: Destroy any data belonging to the future of max_t
            mask_future_t80 = df_summary_dyn["t80_failure_date"] > max_t
            df_summary_dyn.loc[mask_future_t80, ["t80_failure_date", "survival_days"]] = [pd.NaT, np.nan]
            mask_future_ml = df_summary_dyn["ml_alert_date"] > max_t
            df_summary_dyn.loc[mask_future_ml, ["ml_alert_date", "threshold_15pct_day"]] = [pd.NaT, np.nan]
            # TRIPLE Classification (Prevents red bars if it hasn't physically collapsed)
            def classify_state(row):
                if row["t80_occurred"]: return "Physical Collapse"
                if row["ml_occurred"]: return "ML Predictive Alert"
                return "Healthy"

            df_summary_dyn["Current_State"] = df_summary_dyn.apply(classify_state, axis=1)
            # 4. Vectorized KPI Calculation
            n_def_count = int((df_summary_dyn["t80_occurred"] | df_summary_dyn["ml_occurred"]).sum())
            total_ml_cells = len(df_summary_dyn)
            n_val = total_ml_cells - n_def_count
            kpi_p4_val = f"{n_val} / {total_ml_cells}"
            if n_def_count == 0:
                kpi_p4_delta = "100% Operational"
            elif n_val == 0:
                kpi_p4_delta = f"-{n_def_count} Anomalies (Critical)"
            else:
                pct_healthy = (n_val / total_ml_cells) * 100.0
                kpi_p4_delta = f"-{n_def_count} Anomalies ({pct_healthy:.0f}% Healthy)"

            delta_col = "normal"
        else:
            kpi_p4_val, kpi_p4_delta, delta_col = "0 / 0", "No devices", "off"
    else:
        kpi_p4_val, kpi_p4_delta, delta_col = "--", "No ML data", "off"
    # [Render Metrics]
    col_p1, col_p2, col_p3, col_p4 = st.columns(4)
    col_p1.metric("Max Fleet Power", kpi_p1_val, kpi_p1_delta)
    col_p2.metric("Total Energy Received", kpi_p2_val, kpi_p2_delta)
    col_p3.metric("Mean Operative PCE", kpi_p3_val, kpi_p3_delta)
    col_p4.metric("Validated Cells (ML)", kpi_p4_val, kpi_p4_delta, delta_color=delta_col)
    # -------------------------------------------------------------
    # LIFECYCLE ALERT (>14 DAYS) AND DIAGNOSTIC TABLE
    # -------------------------------------------------------------
    st.markdown("<div style='height: 1rem;'></div>", unsafe_allow_html=True)
    if not df_summary_dyn.empty and max_t is not None and not survival_naive_df.empty:

        # 1. Calculate Absolute Day 0
        absolute_day_zero = survival_naive_df.groupby('cell_name').apply(lambda x: x.index.min())

        # Operation end: defaults to max_t (force ns resolution)
        operation_ends = pd.Series(pd.to_datetime(max_t), index=df_summary_dyn.index).astype('datetime64[ns]')

        # BUT if the cell DIED PHYSICALLY, replace its value
        mask_deaths = df_summary_dyn['t80_occurred']
        if mask_deaths.any():
            death_dates = pd.to_datetime(df_summary_dyn.loc[mask_deaths, 't80_failure_date']).astype('datetime64[ns]')
            operation_ends.loc[mask_deaths] = death_dates

        # Real days of exposure to date (or its death)
        exposures = (operation_ends - absolute_day_zero.loc[operation_ends.index]).dt.total_seconds() / 86400.0

        mature_cells = exposures[exposures > 14.0]
        # 2. Render Dynamic Warning if applicable
        if not mature_cells.empty:
            cell_names = ", ".join([f"**{cel}** ({days:.1f} days)" for cel, days in mature_cells.items()])
            st.warning(
                f"⚠️ ***Burn-in* Phase Concluded:** The following cells have exceeded 14 days of outdoor exposure "
                f"by the selected date: {cell_names}. "
                "The Digital Twin window of action has concluded for these devices. "
                "Transition inference to the **Long-Term Predictive Model**."
            )
        # 3. Render Gantt Chart and Table
        with st.expander("View Audit Report (Digital Twin)", expanded=True):
            st.markdown(f"XGBoost Classification adjusted to **{max_t.strftime('%Y-%m-%d %H:%M')}**:")

            df_render = df_summary_dyn.reset_index().copy()

            # --- OPERATION TIME CHART (GANTT) ---
            st.markdown("##### Accumulated Operation Time (Days of Exposure)")

            df_operation = pd.DataFrame({
                'cell_name': exposures.index,
                'Operation_Days': exposures.values,
                'Start': absolute_day_zero.loc[exposures.index].values,
                'End': operation_ends.values
            }).merge(
                df_render[['cell_name', 'Current_State']],
                on='cell_name',
                how='left'
            ).sort_values(by='Operation_Days', ascending=True)
            # Assign semantic color codes
            color_map = {
                'Physical Collapse': '#F43F5E', # Red (Died physically, frozen bar)
                'ML Predictive Alert': '#F59E0B', # Orange (Anomaly detected but still operating)
                'Healthy': '#10B981'            # Green (Healthy, continues operating)
            }
            df_operation['Color'] = df_operation['Current_State'].map(color_map)
            fig_uptime = go.Figure(go.Bar(
                x=df_operation['Operation_Days'],
                y=df_operation['cell_name'],
                orientation='h',
                marker_color=df_operation['Color'],
                text=df_operation['Operation_Days'].apply(lambda x: f"{x:.1f} d"),
                textposition='inside',
                insidetextanchor='middle',
                hovertemplate="<b>%{y}</b><br>" +
                              "Start: %{customdata[0]}<br>" +
                              "End (Death/Today): %{customdata[1]}<br>" +
                              "Operation: %{x:.2f} days<br>" +
                              "Status: %{customdata[2]}<extra></extra>",
                customdata=np.stack((
                    df_operation['Start'].dt.strftime('%Y-%m-%d'),
                    df_operation['End'].dt.strftime('%Y-%m-%d %H:%M'),
                    df_operation['Current_State']
                ), axis=-1)
            ))
            fig_uptime.update_layout(
                margin=dict(l=10, r=10, t=10, b=10),
                plot_bgcolor="white",
                height=150 + (len(df_operation) * 35),
                xaxis=dict(showgrid=True, gridcolor="#F1F5F9", title="Real Days of Exposure"),
                yaxis=dict(showgrid=False)
            )
            st.plotly_chart(fig_uptime, width="stretch", config=plotly_config)
            st.markdown("<hr style='margin: 1.5rem 0; opacity: 0.3;'>", unsafe_allow_html=True)

            # --- ML DIAGNOSTIC TABLE ---
            st.markdown("##### Diagnostics and Anomaly Extraction")

            st.dataframe(
                df_render,
                column_config={
                    "cell_name": "Device",
                    "Current_State": st.column_config.TextColumn("Status (Diagnostic)"),
                    "alert_freq_pct": st.column_config.ProgressColumn(
                        "Alert Frequency (%)", format="%.1f %%", min_value=0, max_value=100
                    ),
                    "threshold_15pct_day": st.column_config.NumberColumn("15% Crossing Day", format="%.1f"),
                    "survival_days": st.column_config.NumberColumn("Survival Days (T80)", format="%.1f"),
                    "t80_failure_date": st.column_config.DatetimeColumn("T80 Date", format="YYYY/MM/DD HH:mm"),
                    "ml_alert_date": st.column_config.DatetimeColumn("ML Alert Date", format="YYYY/MM/DD HH:mm"),
                    "fallo_dinamico": None,
                    "t80_occurred": None,
                    "ml_occurred": None,
                    "extrinsic_failure": None
                },
                hide_index=True,
                width="stretch"
            )
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("#### Comparative Fleet Evolution (Pseudo Fill-Factor)")
    st.markdown("Superposition of the 8 cells under identical outdoor stress conditions.")
    if not survival_df.empty and not plot_df.empty:
        t80_info = calculate_t80_and_survival(survival_df)
        fleet_min_t = plot_df.index.min()
        fleet_max_t = plot_df.index.max()
        df_surv_plot = survival_df[(survival_df.index >= fleet_min_t) & (survival_df.index <= fleet_max_t)]
        if not df_surv_plot.empty:
            pff_wide_df = df_surv_plot.pivot_table(
                index=df_surv_plot.index, columns='cell_name', values='pseudo_FF', aggfunc='mean'
            )
            fleet_fig = create_plotly_chart(df=pff_wide_df, y_cols=list(pff_wide_df.columns), central_metric=selected_metric)
            fleet_fig.update_yaxes(title_text="pFF (Pseudo Fill-Factor)")
            y_min = pff_wide_df.min().min() * 0.95 if not pff_wide_df.empty else 0
            y_max = pff_wide_df.max().max() * 1.05 if not pff_wide_df.empty else 1
            for cell in pff_wide_df.columns:
                info_cell = t80_info.get(cell)
                if info_cell is None: continue
                cell_color = get_trace_color(fleet_fig, cell)
                fleet_fig.add_trace(go.Scatter(
                    x=[fleet_min_t, fleet_max_t], y=[info_cell['t80_threshold'], info_cell['t80_threshold']],
                    mode="lines+text", line=dict(color=cell_color, width=1, dash="dash"),
                    text=[f"T80 {cell}", ""], textposition="top right",
                    textfont=dict(size=9, color=cell_color), showlegend=False, legendgroup=cell, hoverinfo="skip"
                ))
                if info_cell['death_time'] is not None and fleet_min_t <= info_cell['death_time'] <= fleet_max_t:
                    fleet_fig.add_trace(go.Scatter(
                        x=[info_cell['death_time'], info_cell['death_time']], y=[y_min, y_max],
                        mode="lines+text", line=dict(color=cell_color, width=1.5, dash="dot"),
                        text=["", f"Death {cell}"], textposition="top right",
                        textfont=dict(size=9, color=cell_color), showlegend=False, legendgroup=cell, hoverinfo="skip"
                    ))
            st.plotly_chart(fleet_fig, width="stretch", config=plotly_config)
        else:
            st.info("No pFF data recorded for this specific date range.")

# =====================================================================
# VIEW 2: DEVICE ANALYSIS
# =====================================================================
def device_analysis():
    st.sidebar.subheader("Cell Selection")
    target_device = st.sidebar.selectbox("Target Device", ("M83", "P12", "A162", "A164", "A167", "A170", "ASLRX", "M0"))
    st.sidebar.markdown("---")
    st.sidebar.markdown(f"Created by [{CREATOR_LINK.split('/')[-1]}]({CREATOR_LINK}).")
    st.markdown(f"### Unitary Diagnostics — Device **{target_device}**")
    st.caption("Detailed evaluation of electrical parameters and degradation indicators.")
    st.markdown("<div style='height: 0.4rem;'></div>", unsafe_allow_html=True)
    with st.container(border=True):
        col_label, col_control = st.columns([1, 4], vertical_alignment="center")
        with col_label:
            st.markdown("** Time Window**")
        with col_control:
            st.segmented_control("Device Range", options=["Last Sweep", "Weekly", "Historical"], default="Last Sweep", label_visibility="collapsed")
    st.markdown("<div style='height: 0.6rem;'></div>", unsafe_allow_html=True)
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("State of Health (SoH)", "88.4 %", "-1.2%")
    col2.metric("Current pFF", "0.68", "-0.02")
    col3.metric("Anomalies (Isolation Forest)", "Normal", "Stable")
    col4.metric("Estimated Lifespan", "1,450 h", "-40 h")
    st.markdown("---")
    tab1, tab2, tab3, tab4 = st.tabs(["Health (pFF)", "J-V Kinematics", "Prognostics (XGBoost)", "LLM Diagnostics"])
    with tab1:
        st.markdown("### Historical Evolution of Pseudo Fill-Factor (pFF)")
        pff_cell = pd.DataFrame({"pFF": np.linspace(0.75, 0.55, 100) + np.random.normal(0, 0.02, 100)}, index=dates_index)
        fig_t1 = go.Figure(go.Scatter(x=pff_cell.index, y=pff_cell["pFF"], line=dict(color="#10B981")))
        fig_t1.update_layout(margin=dict(l=10, r=10, t=10, b=10), plot_bgcolor="white")
        st.plotly_chart(fig_t1, width="stretch", config=plotly_config)
    with tab2:
        st.markdown("### J-V Characteristic Curves (Reverse / Forward Scans)")
        voltage = np.linspace(-0.2, 1.2, 100)
        j_forward = 22 * (1 - np.exp(10 * (voltage - 1.05)))
        fig_t2 = go.Figure(go.Scatter(x=voltage, y=j_forward, line=dict(color="#F43F5E")))
        fig_t2.update_layout(margin=dict(l=10, r=10, t=10, b=10), plot_bgcolor="white")
        st.plotly_chart(fig_t2, width="stretch", config=plotly_config)
    with tab3:
        st.markdown("### Degradation Projection (XGBoost Engine with Monotonicity)")
        projection = np.linspace(0, 100, 50)
        damage = np.log1p(projection) * 20
        fig_t3 = go.Figure(go.Scatter(x=projection, y=damage, line=dict(color="#8B5CF6")))
        fig_t3.update_layout(margin=dict(l=10, r=10, t=10, b=10), plot_bgcolor="white")
        st.plotly_chart(fig_t3, width="stretch", config=plotly_config)
    with tab4:
        st.markdown("### Thermodynamic Report & Explainability (XAI + LLM)")
        st.info(f"Diagnostic report for cell {target_device}: SHAP values indicate that the pFF drop is highly conditioned by thermal accumulation during irradiance peaks in Seville. Monitoring hysteresis in the next sweep cycle is advised.")
# =====================================================================
# APP STARTUP
# =====================================================================
load_styles()
render_branding()
general_page = st.Page(general_overview, title="General Overview", icon=":material/dashboard:")
device_page = st.Page(device_analysis, title="Device Analysis", icon=":material/troubleshoot:")
pg = st.navigation({"ANALYSIS MODULES": [general_page, device_page]})
pg.run()